// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: compute.proto
#ifndef GRPC_compute_2eproto__INCLUDED
#define GRPC_compute_2eproto__INCLUDED

#include "compute.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace compute {

class ComputeService final {
 public:
  static constexpr char const* service_full_name() {
    return "compute.ComputeService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SumMatrix(::grpc::ClientContext* context, const ::compute::MatrixRequest& request, ::compute::MatrixReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compute::MatrixReply>> AsyncSumMatrix(::grpc::ClientContext* context, const ::compute::MatrixRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compute::MatrixReply>>(AsyncSumMatrixRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compute::MatrixReply>> PrepareAsyncSumMatrix(::grpc::ClientContext* context, const ::compute::MatrixRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compute::MatrixReply>>(PrepareAsyncSumMatrixRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SumMatrix(::grpc::ClientContext* context, const ::compute::MatrixRequest* request, ::compute::MatrixReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SumMatrix(::grpc::ClientContext* context, const ::compute::MatrixRequest* request, ::compute::MatrixReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::compute::MatrixReply>* AsyncSumMatrixRaw(::grpc::ClientContext* context, const ::compute::MatrixRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::compute::MatrixReply>* PrepareAsyncSumMatrixRaw(::grpc::ClientContext* context, const ::compute::MatrixRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SumMatrix(::grpc::ClientContext* context, const ::compute::MatrixRequest& request, ::compute::MatrixReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compute::MatrixReply>> AsyncSumMatrix(::grpc::ClientContext* context, const ::compute::MatrixRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compute::MatrixReply>>(AsyncSumMatrixRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compute::MatrixReply>> PrepareAsyncSumMatrix(::grpc::ClientContext* context, const ::compute::MatrixRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compute::MatrixReply>>(PrepareAsyncSumMatrixRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SumMatrix(::grpc::ClientContext* context, const ::compute::MatrixRequest* request, ::compute::MatrixReply* response, std::function<void(::grpc::Status)>) override;
      void SumMatrix(::grpc::ClientContext* context, const ::compute::MatrixRequest* request, ::compute::MatrixReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::compute::MatrixReply>* AsyncSumMatrixRaw(::grpc::ClientContext* context, const ::compute::MatrixRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::compute::MatrixReply>* PrepareAsyncSumMatrixRaw(::grpc::ClientContext* context, const ::compute::MatrixRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SumMatrix_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SumMatrix(::grpc::ServerContext* context, const ::compute::MatrixRequest* request, ::compute::MatrixReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SumMatrix : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SumMatrix() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SumMatrix() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SumMatrix(::grpc::ServerContext* /*context*/, const ::compute::MatrixRequest* /*request*/, ::compute::MatrixReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSumMatrix(::grpc::ServerContext* context, ::compute::MatrixRequest* request, ::grpc::ServerAsyncResponseWriter< ::compute::MatrixReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SumMatrix<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SumMatrix : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SumMatrix() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::compute::MatrixRequest, ::compute::MatrixReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::compute::MatrixRequest* request, ::compute::MatrixReply* response) { return this->SumMatrix(context, request, response); }));}
    void SetMessageAllocatorFor_SumMatrix(
        ::grpc::MessageAllocator< ::compute::MatrixRequest, ::compute::MatrixReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::compute::MatrixRequest, ::compute::MatrixReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SumMatrix() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SumMatrix(::grpc::ServerContext* /*context*/, const ::compute::MatrixRequest* /*request*/, ::compute::MatrixReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SumMatrix(
      ::grpc::CallbackServerContext* /*context*/, const ::compute::MatrixRequest* /*request*/, ::compute::MatrixReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SumMatrix<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SumMatrix : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SumMatrix() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SumMatrix() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SumMatrix(::grpc::ServerContext* /*context*/, const ::compute::MatrixRequest* /*request*/, ::compute::MatrixReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SumMatrix : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SumMatrix() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SumMatrix() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SumMatrix(::grpc::ServerContext* /*context*/, const ::compute::MatrixRequest* /*request*/, ::compute::MatrixReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSumMatrix(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SumMatrix : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SumMatrix() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SumMatrix(context, request, response); }));
    }
    ~WithRawCallbackMethod_SumMatrix() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SumMatrix(::grpc::ServerContext* /*context*/, const ::compute::MatrixRequest* /*request*/, ::compute::MatrixReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SumMatrix(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SumMatrix : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SumMatrix() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::compute::MatrixRequest, ::compute::MatrixReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::compute::MatrixRequest, ::compute::MatrixReply>* streamer) {
                       return this->StreamedSumMatrix(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SumMatrix() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SumMatrix(::grpc::ServerContext* /*context*/, const ::compute::MatrixRequest* /*request*/, ::compute::MatrixReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSumMatrix(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::compute::MatrixRequest,::compute::MatrixReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SumMatrix<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SumMatrix<Service > StreamedService;
};

}  // namespace compute


#endif  // GRPC_compute_2eproto__INCLUDED
