// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_compute_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_compute_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_compute_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_compute_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_compute_2eproto;
namespace compute {
class MatrixReply;
struct MatrixReplyDefaultTypeInternal;
extern MatrixReplyDefaultTypeInternal _MatrixReply_default_instance_;
class MatrixRequest;
struct MatrixRequestDefaultTypeInternal;
extern MatrixRequestDefaultTypeInternal _MatrixRequest_default_instance_;
}  // namespace compute
PROTOBUF_NAMESPACE_OPEN
template<> ::compute::MatrixReply* Arena::CreateMaybeMessage<::compute::MatrixReply>(Arena*);
template<> ::compute::MatrixRequest* Arena::CreateMaybeMessage<::compute::MatrixRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace compute {

// ===================================================================

class MatrixRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:compute.MatrixRequest) */ {
 public:
  inline MatrixRequest() : MatrixRequest(nullptr) {}
  ~MatrixRequest() override;
  explicit PROTOBUF_CONSTEXPR MatrixRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MatrixRequest(const MatrixRequest& from);
  MatrixRequest(MatrixRequest&& from) noexcept
    : MatrixRequest() {
    *this = ::std::move(from);
  }

  inline MatrixRequest& operator=(const MatrixRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline MatrixRequest& operator=(MatrixRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MatrixRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const MatrixRequest* internal_default_instance() {
    return reinterpret_cast<const MatrixRequest*>(
               &_MatrixRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MatrixRequest& a, MatrixRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(MatrixRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MatrixRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MatrixRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MatrixRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MatrixRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MatrixRequest& from) {
    MatrixRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MatrixRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "compute.MatrixRequest";
  }
  protected:
  explicit MatrixRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1,
    kRowsFieldNumber = 2,
    kColsFieldNumber = 3,
  };
  // repeated double data = 1;
  int data_size() const;
  private:
  int _internal_data_size() const;
  public:
  void clear_data();
  private:
  double _internal_data(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_data() const;
  void _internal_add_data(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_data();
  public:
  double data(int index) const;
  void set_data(int index, double value);
  void add_data(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      data() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_data();

  // int32 rows = 2;
  void clear_rows();
  int32_t rows() const;
  void set_rows(int32_t value);
  private:
  int32_t _internal_rows() const;
  void _internal_set_rows(int32_t value);
  public:

  // int32 cols = 3;
  void clear_cols();
  int32_t cols() const;
  void set_cols(int32_t value);
  private:
  int32_t _internal_cols() const;
  void _internal_set_cols(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:compute.MatrixRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > data_;
    int32_t rows_;
    int32_t cols_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_compute_2eproto;
};
// -------------------------------------------------------------------

class MatrixReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:compute.MatrixReply) */ {
 public:
  inline MatrixReply() : MatrixReply(nullptr) {}
  ~MatrixReply() override;
  explicit PROTOBUF_CONSTEXPR MatrixReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MatrixReply(const MatrixReply& from);
  MatrixReply(MatrixReply&& from) noexcept
    : MatrixReply() {
    *this = ::std::move(from);
  }

  inline MatrixReply& operator=(const MatrixReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline MatrixReply& operator=(MatrixReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MatrixReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const MatrixReply* internal_default_instance() {
    return reinterpret_cast<const MatrixReply*>(
               &_MatrixReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(MatrixReply& a, MatrixReply& b) {
    a.Swap(&b);
  }
  inline void Swap(MatrixReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MatrixReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MatrixReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MatrixReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MatrixReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MatrixReply& from) {
    MatrixReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MatrixReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "compute.MatrixReply";
  }
  protected:
  explicit MatrixReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 1,
  };
  // double result = 1;
  void clear_result();
  double result() const;
  void set_result(double value);
  private:
  double _internal_result() const;
  void _internal_set_result(double value);
  public:

  // @@protoc_insertion_point(class_scope:compute.MatrixReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double result_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_compute_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MatrixRequest

// repeated double data = 1;
inline int MatrixRequest::_internal_data_size() const {
  return _impl_.data_.size();
}
inline int MatrixRequest::data_size() const {
  return _internal_data_size();
}
inline void MatrixRequest::clear_data() {
  _impl_.data_.Clear();
}
inline double MatrixRequest::_internal_data(int index) const {
  return _impl_.data_.Get(index);
}
inline double MatrixRequest::data(int index) const {
  // @@protoc_insertion_point(field_get:compute.MatrixRequest.data)
  return _internal_data(index);
}
inline void MatrixRequest::set_data(int index, double value) {
  _impl_.data_.Set(index, value);
  // @@protoc_insertion_point(field_set:compute.MatrixRequest.data)
}
inline void MatrixRequest::_internal_add_data(double value) {
  _impl_.data_.Add(value);
}
inline void MatrixRequest::add_data(double value) {
  _internal_add_data(value);
  // @@protoc_insertion_point(field_add:compute.MatrixRequest.data)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
MatrixRequest::_internal_data() const {
  return _impl_.data_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
MatrixRequest::data() const {
  // @@protoc_insertion_point(field_list:compute.MatrixRequest.data)
  return _internal_data();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
MatrixRequest::_internal_mutable_data() {
  return &_impl_.data_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
MatrixRequest::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:compute.MatrixRequest.data)
  return _internal_mutable_data();
}

// int32 rows = 2;
inline void MatrixRequest::clear_rows() {
  _impl_.rows_ = 0;
}
inline int32_t MatrixRequest::_internal_rows() const {
  return _impl_.rows_;
}
inline int32_t MatrixRequest::rows() const {
  // @@protoc_insertion_point(field_get:compute.MatrixRequest.rows)
  return _internal_rows();
}
inline void MatrixRequest::_internal_set_rows(int32_t value) {
  
  _impl_.rows_ = value;
}
inline void MatrixRequest::set_rows(int32_t value) {
  _internal_set_rows(value);
  // @@protoc_insertion_point(field_set:compute.MatrixRequest.rows)
}

// int32 cols = 3;
inline void MatrixRequest::clear_cols() {
  _impl_.cols_ = 0;
}
inline int32_t MatrixRequest::_internal_cols() const {
  return _impl_.cols_;
}
inline int32_t MatrixRequest::cols() const {
  // @@protoc_insertion_point(field_get:compute.MatrixRequest.cols)
  return _internal_cols();
}
inline void MatrixRequest::_internal_set_cols(int32_t value) {
  
  _impl_.cols_ = value;
}
inline void MatrixRequest::set_cols(int32_t value) {
  _internal_set_cols(value);
  // @@protoc_insertion_point(field_set:compute.MatrixRequest.cols)
}

// -------------------------------------------------------------------

// MatrixReply

// double result = 1;
inline void MatrixReply::clear_result() {
  _impl_.result_ = 0;
}
inline double MatrixReply::_internal_result() const {
  return _impl_.result_;
}
inline double MatrixReply::result() const {
  // @@protoc_insertion_point(field_get:compute.MatrixReply.result)
  return _internal_result();
}
inline void MatrixReply::_internal_set_result(double value) {
  
  _impl_.result_ = value;
}
inline void MatrixReply::set_result(double value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:compute.MatrixReply.result)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace compute

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_compute_2eproto
