// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute.proto

#include "compute.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace compute {
PROTOBUF_CONSTEXPR MatrixRequest::MatrixRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.data_)*/{}
  , /*decltype(_impl_.rows_)*/0
  , /*decltype(_impl_.cols_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MatrixRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MatrixRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MatrixRequestDefaultTypeInternal() {}
  union {
    MatrixRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MatrixRequestDefaultTypeInternal _MatrixRequest_default_instance_;
PROTOBUF_CONSTEXPR MatrixReply::MatrixReply(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.result_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MatrixReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MatrixReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MatrixReplyDefaultTypeInternal() {}
  union {
    MatrixReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MatrixReplyDefaultTypeInternal _MatrixReply_default_instance_;
}  // namespace compute
static ::_pb::Metadata file_level_metadata_compute_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_compute_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_compute_2eproto = nullptr;

const uint32_t TableStruct_compute_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::compute::MatrixRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::compute::MatrixRequest, _impl_.data_),
  PROTOBUF_FIELD_OFFSET(::compute::MatrixRequest, _impl_.rows_),
  PROTOBUF_FIELD_OFFSET(::compute::MatrixRequest, _impl_.cols_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::compute::MatrixReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::compute::MatrixReply, _impl_.result_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::compute::MatrixRequest)},
  { 9, -1, -1, sizeof(::compute::MatrixReply)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::compute::_MatrixRequest_default_instance_._instance,
  &::compute::_MatrixReply_default_instance_._instance,
};

const char descriptor_table_protodef_compute_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rcompute.proto\022\007compute\"9\n\rMatrixReques"
  "t\022\014\n\004data\030\001 \003(\001\022\014\n\004rows\030\002 \001(\005\022\014\n\004cols\030\003 "
  "\001(\005\"\035\n\013MatrixReply\022\016\n\006result\030\001 \001(\0012K\n\016Co"
  "mputeService\0229\n\tSumMatrix\022\026.compute.Matr"
  "ixRequest\032\024.compute.MatrixReplyb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_compute_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_compute_2eproto = {
    false, false, 199, descriptor_table_protodef_compute_2eproto,
    "compute.proto",
    &descriptor_table_compute_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_compute_2eproto::offsets,
    file_level_metadata_compute_2eproto, file_level_enum_descriptors_compute_2eproto,
    file_level_service_descriptors_compute_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_compute_2eproto_getter() {
  return &descriptor_table_compute_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_compute_2eproto(&descriptor_table_compute_2eproto);
namespace compute {

// ===================================================================

class MatrixRequest::_Internal {
 public:
};

MatrixRequest::MatrixRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:compute.MatrixRequest)
}
MatrixRequest::MatrixRequest(const MatrixRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MatrixRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){from._impl_.data_}
    , decltype(_impl_.rows_){}
    , decltype(_impl_.cols_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.rows_, &from._impl_.rows_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.cols_) -
    reinterpret_cast<char*>(&_impl_.rows_)) + sizeof(_impl_.cols_));
  // @@protoc_insertion_point(copy_constructor:compute.MatrixRequest)
}

inline void MatrixRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){arena}
    , decltype(_impl_.rows_){0}
    , decltype(_impl_.cols_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MatrixRequest::~MatrixRequest() {
  // @@protoc_insertion_point(destructor:compute.MatrixRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MatrixRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.data_.~RepeatedField();
}

void MatrixRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MatrixRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:compute.MatrixRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.Clear();
  ::memset(&_impl_.rows_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.cols_) -
      reinterpret_cast<char*>(&_impl_.rows_)) + sizeof(_impl_.cols_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MatrixRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated double data = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 9) {
          _internal_add_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // int32 rows = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.rows_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 cols = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.cols_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MatrixRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:compute.MatrixRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated double data = 1;
  if (this->_internal_data_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_data(), target);
  }

  // int32 rows = 2;
  if (this->_internal_rows() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_rows(), target);
  }

  // int32 cols = 3;
  if (this->_internal_cols() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_cols(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:compute.MatrixRequest)
  return target;
}

size_t MatrixRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:compute.MatrixRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double data = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_data_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // int32 rows = 2;
  if (this->_internal_rows() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_rows());
  }

  // int32 cols = 3;
  if (this->_internal_cols() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_cols());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MatrixRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MatrixRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MatrixRequest::GetClassData() const { return &_class_data_; }


void MatrixRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MatrixRequest*>(&to_msg);
  auto& from = static_cast<const MatrixRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:compute.MatrixRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.data_.MergeFrom(from._impl_.data_);
  if (from._internal_rows() != 0) {
    _this->_internal_set_rows(from._internal_rows());
  }
  if (from._internal_cols() != 0) {
    _this->_internal_set_cols(from._internal_cols());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MatrixRequest::CopyFrom(const MatrixRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:compute.MatrixRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MatrixRequest::IsInitialized() const {
  return true;
}

void MatrixRequest::InternalSwap(MatrixRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.data_.InternalSwap(&other->_impl_.data_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MatrixRequest, _impl_.cols_)
      + sizeof(MatrixRequest::_impl_.cols_)
      - PROTOBUF_FIELD_OFFSET(MatrixRequest, _impl_.rows_)>(
          reinterpret_cast<char*>(&_impl_.rows_),
          reinterpret_cast<char*>(&other->_impl_.rows_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MatrixRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_compute_2eproto_getter, &descriptor_table_compute_2eproto_once,
      file_level_metadata_compute_2eproto[0]);
}

// ===================================================================

class MatrixReply::_Internal {
 public:
};

MatrixReply::MatrixReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:compute.MatrixReply)
}
MatrixReply::MatrixReply(const MatrixReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MatrixReply* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.result_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.result_ = from._impl_.result_;
  // @@protoc_insertion_point(copy_constructor:compute.MatrixReply)
}

inline void MatrixReply::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.result_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MatrixReply::~MatrixReply() {
  // @@protoc_insertion_point(destructor:compute.MatrixReply)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MatrixReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void MatrixReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MatrixReply::Clear() {
// @@protoc_insertion_point(message_clear_start:compute.MatrixReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MatrixReply::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double result = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _impl_.result_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MatrixReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:compute.MatrixReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // double result = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_result = this->_internal_result();
  uint64_t raw_result;
  memcpy(&raw_result, &tmp_result, sizeof(tmp_result));
  if (raw_result != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_result(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:compute.MatrixReply)
  return target;
}

size_t MatrixReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:compute.MatrixReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double result = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_result = this->_internal_result();
  uint64_t raw_result;
  memcpy(&raw_result, &tmp_result, sizeof(tmp_result));
  if (raw_result != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MatrixReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MatrixReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MatrixReply::GetClassData() const { return &_class_data_; }


void MatrixReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MatrixReply*>(&to_msg);
  auto& from = static_cast<const MatrixReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:compute.MatrixReply)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_result = from._internal_result();
  uint64_t raw_result;
  memcpy(&raw_result, &tmp_result, sizeof(tmp_result));
  if (raw_result != 0) {
    _this->_internal_set_result(from._internal_result());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MatrixReply::CopyFrom(const MatrixReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:compute.MatrixReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MatrixReply::IsInitialized() const {
  return true;
}

void MatrixReply::InternalSwap(MatrixReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.result_, other->_impl_.result_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MatrixReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_compute_2eproto_getter, &descriptor_table_compute_2eproto_once,
      file_level_metadata_compute_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace compute
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::compute::MatrixRequest*
Arena::CreateMaybeMessage< ::compute::MatrixRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::compute::MatrixRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::compute::MatrixReply*
Arena::CreateMaybeMessage< ::compute::MatrixReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::compute::MatrixReply >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
